# Generated by Django 4.2.4 on 2024-08-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
